### ISSUE TITLE
I have some problems when running the demo

### ISSUE THREAD

**Issue by VerseWei** [zju3dv/AutoDecomp#2]
Hello! Many thanks for this great project!

When I run the scripts/run_pipeline_demo_low-res.sh，a terrible error was encountered, as

(extract_and_match pid=6843) /home/xiaosongwei/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/nn/functional.py:4227: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
(extract_and_match pid=6843)   warnings.warn(
  2%|▎         | 1/40 [00:01<00:53,  1.38s/it]
 18%|█▊        | 7/40 [00:01<00:05,  6.25it/s]
 32%|███▎      | 13/40 [00:01<00:02, 12.35it/s]
 48%|████▊     | 19/40 [00:01<00:01, 19.00it/s]
 62%|██████▎   | 25/40 [00:01<00:00, 25.75it/s]
 78%|███████▊  | 31/40 [00:01<00:00, 32.29it/s]
 92%|█████████▎| 37/40 [00:02<00:00, 38.07it/s]
2023-08-14 09:41:13,717 ERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::FeatureActor.run() (pid=6688, ip=10.96.33.83, actor_id=129ef46931ba20e25c757a0801000000, repr=<auto_decomp.sfm.sfm.FeatureActor object at 0x7f79fc0fe2e0>)
  File "/home/xiaosongwei/AutoDecomp/auto_decomp/sfm/sfm.py", line 312, in run
    _ = ray.get(obj_refs)
ray.exceptions.RayTaskError(SyntaxError): <no detail available>

Can you give me some solutions?

**Comment by ChengWan9** [comment]
hello can you share your run_pipeline_demo_low-res.sh？i also met an issue but i dont know how to solve it.
I think there may be a problem with my file path.
Can you help me?Thank you.

**Comment by VerseWei** [comment]
My demo is as follows，good luck！

DATA_ROOT=/home/wxs/3D_Recon/AutoRecon/third_party/AutoDecomp/assets/
INST_REL_DIR=custom_data_example/co3d_chair
FORCE_RERUN=True

# Coarse decomposition
python /home/wxs/3D_Recon/AutoRecon/third_party/AutoDecomp/auto_decomp/cli/inference_transformer.py --config-name=cvpr \
    data_root=$DATA_ROOT \
    inst_rel_dir=$INST_REL_DIR \
    sparse_recon.n_images=40 \
    sparse_recon.force_rerun=$FORCE_RERUN \
    sparse_recon.n_feature_workers=1 sparse_recon.n_rec

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/13/2023 17:13 |
| To | zju3dv/AutoDecomp ***@***.***> |
| Cc | VerseWei ***@***.***>,
Author ***@***.***> |
| Subject | Re: [zju3dv/AutoDecomp] I have some problems when running the demo (Issue #2) |

hello can you share your run_pipeline_demo_low-res.sh？i also met an issue but i dont know how to solve it.
I think there may be a problem with my file path.
Can you help me?Thank you.

**Comment by ChengWan9** [comment]
> My demo is as follows，good luck！ DATA_ROOT=/home/wxs/3D_Recon/AutoRecon/third_party/AutoDecomp/assets/ INST_REL_DIR=custom_data_example/co3d_chair FORCE_RERUN=True # Coarse decomposition python /home/wxs/3D_Recon/AutoRecon/third_party/AutoDecomp/auto_decomp/cli/inference_transformer.py --config-name=cvpr \ data_root=$DATA_ROOT \ inst_rel_dir=$INST_REL_DIR \ sparse_recon.n_images=40 \ sparse_recon.force_rerun=$FORCE_RERUN \ sparse_recon.n_feature_workers=1 sparse_recon.n_rec
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 10/13/2023 17:13 | | To | zju3dv/AutoDecomp ***@***.***> | | Cc | VerseWei ***@***.***>, Author ***@***.***> | | Subject | Re: [zju3dv/AutoDecomp] I have some problems when running the demo (Issue #2) | hello can you share your run_pipeline_demo_low-res.sh？i also met an issue but i dont know how to solve it. I think there may be a problem with my file path. Can you help me?Thank you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

thanks for your apply,but it didnt work for me,it always say could not read bytes. QAQ
